version: 2 # use CircleCI 2.0
orbs:
  heroku: circleci/heroku@1.0.0
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
jobs: # a collection of steps
  deploy:
    docker:
      - image: buildpack-deps:trusty # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:3b0c0f5b-2e1c-40c2-ac9f-5d62773640e0@git.heroku.com/node-circle-app.git master
